name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Build geoip
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NO_SKIP: true
        run: go run -v .
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: geoip.db
          path: geoip.db
